### ISSUE TITLE
(NOT AN ISSUE its a request)

### ISSUE THREAD

**Issue by vysex** [YonLiud/Emergency-Caller#4]
Not an issue but I think it would be a great idea to add a discoes webhook command so it could be seen on a PD discord channel if no dispatch is active.

**Comment by YonLiud** [comment]
unfortunately, I don't plan on adding a webhook trigger, Sorry.
**But**, I found useful resources that might help you add the webhook trigger into the script:
[https://pastebin.com/W6mMjNDz](https://pastebin.com/W6mMjNDz)

if you wish to contribute this suggestion to the script, feel free to fork, add and create a pull request with the added script!
